/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Employee;

import Business.*;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Wenqing
 */
public class EmployeeLoginPanel extends javax.swing.JPanel {
    private SupplierDirectory sd;
    private MarketOfferCatalogue moc;
    private MarketList ml;
    private PersonDirectory pd;
    private UserAccountDirectory uad;
    
    private JPanel card;

    public EmployeeLoginPanel(JPanel CardPanel, SupplierDirectory sd, MarketOfferCatalogue moc, MarketList ml, PersonDirectory pd, UserAccountDirectory uad) {
        initComponents();
        this.card = CardPanel;
        this.sd = sd;
        this.moc =moc;
        this.ml = ml;
        this.uad = uad;
        this.pd =pd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        UserTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PassTxt = new javax.swing.JTextField();
        butLogin = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("User Name:");

        UserTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Password:");

        PassTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        butLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        butLogin.setText("Log In");
        butLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(UserTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(PassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(UserTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(butLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLoginActionPerformed
        if(UserTxt.getText().isEmpty() || PassTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter both username and password");
            return;
        }
        if(uad.isValidUser(UserTxt.getText(), PassTxt.getText())!=null){
            for(UserAccount ua: uad.getList()){
                if(ua.getUserName().equals(UserTxt.getText())){
                    if(ua.getRole().equals("admin")){
                    Person p = ua.getP();
                    SystemAdminPanel sap = new SystemAdminPanel(card, p, sd, moc, ml, uad, pd);
                    card.add("SystemAdminPanel", sap);
                    CardLayout lo = (CardLayout) card.getLayout();
                    lo.next(card);
                }
                    if(ua.getRole().equals("sales person")){
                        Person p = ua.getP();
                        SalesmanWorkingPanel swp = new SalesmanWorkingPanel(card, sd, moc, ml, p);
                        card.add("SalesmanWorkingPanel", swp);
                        CardLayout lo = (CardLayout) card.getLayout();
                        lo.next(card);
                    }
                }                    
            }
            UserTxt.setText("");
            PassTxt.setText("");
        }         
        else {
             JOptionPane.showMessageDialog(null,"Username and Password do not match with system records");
        }  
    }//GEN-LAST:event_butLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PassTxt;
    private javax.swing.JTextField UserTxt;
    private javax.swing.JButton butLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
