/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Employee;

import Business.MarketList;
import Business.MarketOffer;
import Business.MarketOfferCatalogue;
import Business.PersonDirectory;
import Business.Supplier;
import Business.SupplierDirectory;
import Business.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tianchenglin
 */
public class ManageMarketOfferPanel extends javax.swing.JPanel {
    
    private JPanel card;
    private MarketOfferCatalogue moc;
    private MarketList ml;
    private SupplierDirectory sd;

    /**
     * Creates new form ManageMarketOfferPanel
     */

    ManageMarketOfferPanel(JPanel card, SupplierDirectory sd, MarketOfferCatalogue moc, MarketList ml, UserAccountDirectory uad, PersonDirectory pd) {
        initComponents();
        this.card = card;
        this.moc = moc;
        this.ml = ml;
        this.sd = sd;
        
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblMarketOffer.getModel();
        dtm.setRowCount(0);
        for(MarketOffer mo: moc.getList()){
            Object row[] = new Object[5];
            row[0] = mo;
            row[1] = mo.getM().getMarketName();
            row[2] = mo.getFloorPrice();
            row[3] = mo.getTargetPrice();
            row[4] = mo.getCeilingPrice();
            
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMarketOffer = new javax.swing.JTable();
        BackBut = new javax.swing.JButton();
        RemoveBut = new javax.swing.JButton();
        NewBut = new javax.swing.JButton();
        ViewBut = new javax.swing.JButton();

        jLabel1.setText("Market Offer:");

        tblMarketOffer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product", "Market", "Floor price", "Target price", "Celling price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMarketOffer);

        BackBut.setText("< Back");
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });

        RemoveBut.setText("Remove");
        RemoveBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButActionPerformed(evt);
            }
        });

        NewBut.setText("New");
        NewBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewButActionPerformed(evt);
            }
        });

        ViewBut.setText("View");
        ViewBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackBut)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RemoveBut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ViewBut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NewBut))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackBut)
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoveBut)
                    .addComponent(NewBut)
                    .addComponent(ViewBut))
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
        // TODO add your handling code here:
        card.remove(this);
        CardLayout layout = (CardLayout) card.getLayout();
        layout.previous(card);
    }//GEN-LAST:event_BackButActionPerformed

    private void RemoveButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButActionPerformed
        // TODO add your handling code here:
        int row = tblMarketOffer.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        MarketOffer mo = (MarketOffer) tblMarketOffer.getValueAt(row, 0);
        moc.deleteMarketOffer(mo);
        populateTable();
        
    }//GEN-LAST:event_RemoveButActionPerformed

    private void NewButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewButActionPerformed
        // TODO add your handling code here:
        AddMarketOfferPanel amop = new AddMarketOfferPanel(card, moc, ml, sd);
        card.add("AddMarketOfferPanel", amop);
        CardLayout layout = (CardLayout) card.getLayout();
        layout.next(card);
        
        
    }//GEN-LAST:event_NewButActionPerformed

    private void ViewButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButActionPerformed
        // TODO add your handling code here:
        int row= tblMarketOffer.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        MarketOffer mo = (MarketOffer) tblMarketOffer.getValueAt(row, 0);
        ViewMarketOfferPanel vmop = new ViewMarketOfferPanel(card, moc, ml, sd, mo);
        card.add("ViewMarketOfferPanel", vmop);
        CardLayout layout = (CardLayout) card.getLayout();
        layout.next(card);
    }//GEN-LAST:event_ViewButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBut;
    private javax.swing.JButton NewBut;
    private javax.swing.JButton RemoveBut;
    private javax.swing.JButton ViewBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMarketOffer;
    // End of variables declaration//GEN-END:variables
}
