/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CharityAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CharityAdminOrganization;
import Business.Organization.Organization;
import Business.Organization.PeopleManagingOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FundRequest;
import Business.WorkQueue.PeopleInfoRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tianchenglin
 */
public class CharityAdminWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private CharityAdminOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem sys;

    /**
     * Creates new form CharityAdminWorkAreaJPanel
     */
   

    public CharityAdminWorkAreaJPanel(JPanel card, UserAccount account, CharityAdminOrganization charityAdminOrganization, Enterprise ent, EcoSystem business) {

        initComponents();
        this.userProcessContainer = card;
        this.organization = charityAdminOrganization;
        this.enterprise = ent;
        this.userAccount = account;
        this.sys = business;
        NameTxt.setText(enterprise.getName());
        populatePeopleInfoTable();
    }
    
    public void populatePeopleInfoTable(){
        DefaultTableModel model = (DefaultTableModel)PeopleInfoTable.getModel();
        model.setRowCount(0);
        
        for(Network n: sys.getNetworkList()){
            for(Enterprise e: n.getEnterpriseDirectory().getEnterpriseList()){
                for(Organization o: e.getOrganizationDirectory().getOrganizationList()){
                    if(o instanceof PeopleManagingOrganization){
                        System.out.print(o);
                        for(WorkRequest request: o.getWorkQueue().getWorkRequestList()){
                            Object[] row = new Object[5];
                            row[0] = ((PeopleInfoRequest)request).getPeople();
                            row[1] = ((PeopleInfoRequest)request).getAge();
                            row[2] = ((PeopleInfoRequest)request).getGender();
                            row[3] = ((PeopleInfoRequest)request).getMedicalHistory();
                            row[4] = ((PeopleInfoRequest)request).getInsuranceType();

                            model.addRow(row);
                        }
                    }
                }
            }
        }
//        for(WorkRequest request : peopleManagingOrganization.getWorkQueue().getWorkRequestList()){
//            Object[] row = new Object[5];
//            row[0] = ((PeopleInfoRequest)request).getName();
//            row[1] = ((PeopleInfoRequest)request).getAge();
//            row[2] = ((PeopleInfoRequest)request).getGender();
//            row[3] = ((PeopleInfoRequest)request).getMedicalHistory();
//            row[4] = ((PeopleInfoRequest)request).getInsuranceType();
//            
//            model.addRow(row);
//        }
    }
      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        PeopleInfoTable = new javax.swing.JTable();
        QuoteRequestBut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");

        NameTxt.setEnabled(false);

        PeopleInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "Gender", "Medical History", "Insurance Type"
            }
        ));
        jScrollPane2.setViewportView(PeopleInfoTable);

        QuoteRequestBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        QuoteRequestBut.setText("Request Insurance Quote");
        QuoteRequestBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuoteRequestButActionPerformed(evt);
            }
        });

        jLabel1.setText("Homeless People Request Directory:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(11, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(QuoteRequestBut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(QuoteRequestBut)
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void QuoteRequestButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuoteRequestButActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestInsuranceQuotePanel", new RequestInsuranceQuotePanel(userProcessContainer, userAccount, organization, enterprise, sys));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_QuoteRequestButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NameTxt;
    private javax.swing.JTable PeopleInfoTable;
    private javax.swing.JButton QuoteRequestBut;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}