/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
 
import Business.*;

/**
 *
 * @author Wenqing
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    public ViewPanel(Address add, CreditCard cc, FinancialAcc fa, License li, Person per) {
        initComponents();
        displayPanel(add,cc,fa,li,per);
    }
    private void displayPanel(Address add, CreditCard cc, FinancialAcc fa, License li, Person per) {
        if(add.getAptNo()!= 0){
            AptNoTxt.setText(Integer.toString(add.getAptNo()));
        }        
        StreetAddTxt.setText(add.getStreetAdd());
        AddStateTxt.setText(add.getState());
        ZipTxt.setText(add.getZip());
        CountryTxt.setText(add.getCountry());
        
        BillingAddTxt.setText(cc.getBillingAdd());
        if(cc.getContactPhone()!=0){
            PhoneTxt.setText(Integer.toString(cc.getContactPhone()));
        }        
        CVVtxt.setText(cc.getCvv());
        ExpDateTxt.setText(cc.getExpDate());
        CardNoTxt.setText(Long.toString(cc.getNumber()));
        
        String URL = per.getProfilePicture();
        ImageLabel.setText(URL);        
        FirstNameTxt.setText(per.getFirstName());
        LastNameTxt.setText(per.getLastName());
        DOBtxt.setText(per.getDateOfBirth());
        if(per.getAge()!=0){
            AgeTxt.setText(Integer.toString(per.getAge()));
        }        
        GenderTxt.setText(per.getGender());        
          
        ExpirationDateTxt.setText(li.getExpDate());
        IssueDateTxt.setText(li.getIssueDate());
        LicenseClassTxt.setText(li.getLicenseClass());
        LicenseNoTxt.setText(li.getLicenseNo());
        StateTXT.setText(li.getState());
        
        if(fa.getCheckingAccNo()!=0){
            CheckingAccNoTxt.setText(Long.toString(fa.getCheckingAccNo()));
        }        
        CheckingCreaDateTxt.setText(fa.getCreationDateChecking());
        CheckingCreditTxt.setText(fa.getCreditChecking());
        CheckingDebtTxt.setText(fa.getDebtChecking());
        Boolean b1 = fa.isIsActiveChecking();
        if(b1==true){
            CheckingStillActiveTxt.setText("yes");
        }
        else{
            CheckingStillActiveTxt.setText("no");
        }
        
        if(fa.getSavingaAccNo()!=0){
            SavingAccNoTxt.setText((Long.toString(fa.getSavingaAccNo())));
        }        
        SavingCreaDateTxt.setText(fa.getCreationDateSaving());
        SavingCreditTxt.setText(fa.getCreditSaving());
        SavingDebtTxt.setText(fa.getDebtSaving());
        Boolean b2 = fa.isIsActiveSaving();
        if(b2==true){
            SavingStillActiveTxt.setText("yes");
        }
        else{
            SavingStillActiveTxt.setText("no");
        }
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PersonPanel = new javax.swing.JPanel();
        DOBtxt = new javax.swing.JTextField();
        AgeTxt = new javax.swing.JTextField();
        GenderTxt = new javax.swing.JTextField();
        FirstNameTxt = new javax.swing.JTextField();
        LastNameTxt = new javax.swing.JTextField();
        FirstNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        DOBLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        personalInfoLabel = new javax.swing.JLabel();
        ProfileLabel = new javax.swing.JLabel();
        ImageLabel = new javax.swing.JLabel();
        LicensePanel = new javax.swing.JPanel();
        LicenseInfoLabel = new javax.swing.JLabel();
        LicenseNoLabel = new javax.swing.JLabel();
        LicenseNoTxt = new javax.swing.JTextField();
        IssueDateLabel = new javax.swing.JLabel();
        IssueDateTxt = new javax.swing.JTextField();
        ExpirationDateLabel = new javax.swing.JLabel();
        ExpirationDateTxt = new javax.swing.JTextField();
        LicenseClassLabel = new javax.swing.JLabel();
        LicenseClassTxt = new javax.swing.JTextField();
        StateLabel = new javax.swing.JLabel();
        StateTXT = new javax.swing.JTextField();
        CreditCardPanel = new javax.swing.JPanel();
        ccInfoLabel = new javax.swing.JLabel();
        CardNoLabel = new javax.swing.JLabel();
        CardNoTxt = new javax.swing.JTextField();
        ExpDateLabel = new javax.swing.JLabel();
        ExpDateTxt = new javax.swing.JTextField();
        CVVlabel = new javax.swing.JLabel();
        CVVtxt = new javax.swing.JTextField();
        BillingAddLabel = new javax.swing.JLabel();
        BillingAddTxt = new javax.swing.JTextField();
        PhoneLabel = new javax.swing.JLabel();
        PhoneTxt = new javax.swing.JTextField();
        AddressPanel = new javax.swing.JPanel();
        AddressLabel = new javax.swing.JLabel();
        StreetAddLabel = new javax.swing.JLabel();
        StreetAddTxt = new javax.swing.JTextField();
        AptNoLabel = new javax.swing.JLabel();
        AptNoTxt = new javax.swing.JTextField();
        AddStateLabel = new javax.swing.JLabel();
        AddStateTxt = new javax.swing.JTextField();
        CountryLabel = new javax.swing.JLabel();
        CountryTxt = new javax.swing.JTextField();
        ZipLabel = new javax.swing.JLabel();
        ZipTxt = new javax.swing.JTextField();
        FinancialAccPanel = new javax.swing.JPanel();
        FinancialAccLabel = new javax.swing.JLabel();
        CheckingAccNoLabel = new javax.swing.JLabel();
        CheckingAccNoTxt = new javax.swing.JTextField();
        CheckingCreaDateLabel = new javax.swing.JLabel();
        CheckingCreaDateTxt = new javax.swing.JTextField();
        CheckingActiveLabel = new javax.swing.JLabel();
        CheckingStillActiveTxt = new javax.swing.JTextField();
        CheckingDebtLabel = new javax.swing.JLabel();
        CheckingDebtTxt = new javax.swing.JTextField();
        CheckingCreditLabel = new javax.swing.JLabel();
        CheckingCreditTxt = new javax.swing.JTextField();
        SavingAccNoLabel = new javax.swing.JLabel();
        SavingAccNoTxt = new javax.swing.JTextField();
        SavingCreaDateLabel = new javax.swing.JLabel();
        SavingCreaDateTxt = new javax.swing.JTextField();
        SavingStillActiveLabel = new javax.swing.JLabel();
        SavingStillActiveTxt = new javax.swing.JTextField();
        SavingDebtLabel = new javax.swing.JLabel();
        SavingDebtTxt = new javax.swing.JTextField();
        SavingCreditLabel = new javax.swing.JLabel();
        SavingCreditTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        PersonPanel.setBackground(new java.awt.Color(204, 204, 204));

        FirstNameLabel.setText("First Name");

        LastNameLabel.setText("Last Name");

        DOBLabel.setText("Date of Birth");

        GenderLabel.setText("Gender");

        AgeLabel.setText("Age");

        personalInfoLabel.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        personalInfoLabel.setText("Personal Information");

        ProfileLabel.setText("Profile Picture");

        ImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Elizabeth_fullbody.png"))); // NOI18N

        javax.swing.GroupLayout PersonPanelLayout = new javax.swing.GroupLayout(PersonPanel);
        PersonPanel.setLayout(PersonPanelLayout);
        PersonPanelLayout.setHorizontalGroup(
            PersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personalInfoLabel)
                    .addGroup(PersonPanelLayout.createSequentialGroup()
                        .addGroup(PersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PersonPanelLayout.createSequentialGroup()
                                .addComponent(DOBLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DOBtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PersonPanelLayout.createSequentialGroup()
                                    .addComponent(FirstNameLabel)
                                    .addGap(20, 20, 20)
                                    .addComponent(FirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PersonPanelLayout.createSequentialGroup()
                                    .addComponent(LastNameLabel)
                                    .addGap(21, 21, 21)
                                    .addComponent(LastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(42, 42, 42)
                        .addGroup(PersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GenderLabel)
                            .addComponent(AgeLabel))
                        .addGap(18, 18, 18)
                        .addGroup(PersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GenderTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(AgeTxt))))
                .addGap(111, 111, 111)
                .addGroup(PersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImageLabel)
                    .addComponent(ProfileLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PersonPanelLayout.setVerticalGroup(
            PersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personalInfoLabel)
                    .addComponent(ProfileLabel))
                .addGroup(PersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersonPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(PersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstNameLabel)
                            .addComponent(GenderLabel)
                            .addComponent(GenderTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(PersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LastNameTxt)
                            .addGroup(PersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LastNameLabel)
                                .addComponent(AgeLabel)
                                .addComponent(AgeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(PersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DOBtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DOBLabel)))
                    .addGroup(PersonPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        LicensePanel.setBackground(new java.awt.Color(204, 204, 204));

        LicenseInfoLabel.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        LicenseInfoLabel.setText("License Info");

        LicenseNoLabel.setText("License No.");

        IssueDateLabel.setText("Issue Date");

        ExpirationDateLabel.setText("Expiration Date");

        LicenseClassLabel.setText("License Class");

        StateLabel.setText("State");

        javax.swing.GroupLayout LicensePanelLayout = new javax.swing.GroupLayout(LicensePanel);
        LicensePanel.setLayout(LicensePanelLayout);
        LicensePanelLayout.setHorizontalGroup(
            LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LicensePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LicenseInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LicensePanelLayout.createSequentialGroup()
                        .addGroup(LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(LicensePanelLayout.createSequentialGroup()
                                .addComponent(LicenseClassLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LicenseClassTxt))
                            .addGroup(LicensePanelLayout.createSequentialGroup()
                                .addComponent(LicenseNoLabel)
                                .addGap(18, 18, 18)
                                .addComponent(LicenseNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addGroup(LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StateLabel)
                            .addComponent(IssueDateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IssueDateTxt)
                            .addComponent(StateTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(ExpirationDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExpirationDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LicensePanelLayout.setVerticalGroup(
            LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LicensePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LicenseInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LicenseNoLabel)
                    .addComponent(LicenseNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IssueDateLabel)
                    .addComponent(IssueDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExpirationDateLabel)
                    .addComponent(ExpirationDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LicensePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LicenseClassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(StateLabel)
                        .addComponent(StateTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LicenseClassLabel))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        CreditCardPanel.setBackground(new java.awt.Color(204, 204, 204));

        ccInfoLabel.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        ccInfoLabel.setText("Credit Card Info");

        CardNoLabel.setText("Card No");

        ExpDateLabel.setText("Exp Date");

        ExpDateTxt.setToolTipText("");

        CVVlabel.setText("CVV");

        BillingAddLabel.setText("Billing Address");

        PhoneLabel.setText("Phone No.");

        javax.swing.GroupLayout CreditCardPanelLayout = new javax.swing.GroupLayout(CreditCardPanel);
        CreditCardPanel.setLayout(CreditCardPanelLayout);
        CreditCardPanelLayout.setHorizontalGroup(
            CreditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreditCardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ccInfoLabel)
                    .addGroup(CreditCardPanelLayout.createSequentialGroup()
                        .addGroup(CreditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CreditCardPanelLayout.createSequentialGroup()
                                .addComponent(BillingAddLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BillingAddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CreditCardPanelLayout.createSequentialGroup()
                                .addComponent(CardNoLabel)
                                .addGap(32, 32, 32)
                                .addComponent(CardNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(ExpDateLabel)
                                .addGap(21, 21, 21)
                                .addComponent(ExpDateTxt)))
                        .addGap(52, 52, 52)
                        .addGroup(CreditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PhoneLabel)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreditCardPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(CVVlabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CreditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CVVtxt)
                            .addComponent(PhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        CreditCardPanelLayout.setVerticalGroup(
            CreditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreditCardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ccInfoLabel)
                .addGap(6, 6, 6)
                .addGroup(CreditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CardNoLabel)
                    .addComponent(CardNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExpDateLabel)
                    .addComponent(ExpDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CVVlabel)
                    .addComponent(CVVtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreditCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BillingAddLabel)
                    .addComponent(BillingAddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        AddressPanel.setBackground(new java.awt.Color(204, 204, 204));

        AddressLabel.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        AddressLabel.setText("Address");

        StreetAddLabel.setText("Street Address");

        AptNoLabel.setText("Apt No.");

        AddStateLabel.setText("State");

        CountryLabel.setText("Country");

        ZipLabel.setText("ZipCode");

        javax.swing.GroupLayout AddressPanelLayout = new javax.swing.GroupLayout(AddressPanel);
        AddressPanel.setLayout(AddressPanelLayout);
        AddressPanelLayout.setHorizontalGroup(
            AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddressLabel)
                    .addGroup(AddressPanelLayout.createSequentialGroup()
                        .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StreetAddLabel)
                            .addComponent(AddStateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StreetAddTxt)
                            .addComponent(AddStateTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AptNoLabel)
                            .addComponent(CountryLabel))
                        .addGap(28, 28, 28)
                        .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CountryTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(AptNoTxt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(50, 50, 50)
                        .addComponent(ZipLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ZipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddressPanelLayout.setVerticalGroup(
            AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddressLabel)
                .addGap(4, 4, 4)
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StreetAddLabel)
                    .addComponent(StreetAddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AptNoLabel)
                    .addComponent(AptNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZipLabel)
                    .addComponent(ZipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddStateLabel)
                    .addComponent(AddStateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CountryLabel)
                    .addComponent(CountryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FinancialAccPanel.setBackground(new java.awt.Color(204, 204, 204));

        FinancialAccLabel.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        FinancialAccLabel.setText("Financial Account");

        CheckingAccNoLabel.setText("Checking Account No.");

        CheckingCreaDateLabel.setText("Creation Date");

        CheckingActiveLabel.setText("Still Active");

        CheckingDebtLabel.setText("Debt");

        CheckingCreditLabel.setText("Credit");

        SavingAccNoLabel.setText("Saving Account No.");

        SavingCreaDateLabel.setText("Creation Date");

        SavingStillActiveLabel.setText("Still Active");

        SavingDebtLabel.setText("Debt");

        SavingCreditLabel.setText("Credit");

        jLabel1.setText("(yes/no)");

        jLabel2.setText("(yes/no)");

        javax.swing.GroupLayout FinancialAccPanelLayout = new javax.swing.GroupLayout(FinancialAccPanel);
        FinancialAccPanel.setLayout(FinancialAccPanelLayout);
        FinancialAccPanelLayout.setHorizontalGroup(
            FinancialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinancialAccPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FinancialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FinancialAccLabel)
                    .addGroup(FinancialAccPanelLayout.createSequentialGroup()
                        .addGroup(FinancialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckingAccNoLabel)
                            .addComponent(CheckingDebtLabel)
                            .addComponent(SavingAccNoLabel)
                            .addComponent(SavingDebtLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FinancialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CheckingAccNoTxt)
                            .addComponent(CheckingDebtTxt)
                            .addComponent(SavingAccNoTxt)
                            .addComponent(SavingDebtTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(FinancialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(FinancialAccPanelLayout.createSequentialGroup()
                                .addGroup(FinancialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CheckingCreaDateLabel)
                                    .addComponent(CheckingCreditLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(FinancialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CheckingCreaDateTxt)
                                    .addComponent(CheckingCreditTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)))
                            .addGroup(FinancialAccPanelLayout.createSequentialGroup()
                                .addGroup(FinancialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SavingCreaDateLabel)
                                    .addComponent(SavingCreditLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(FinancialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SavingCreaDateTxt)
                                    .addComponent(SavingCreditTxt))))
                        .addGap(18, 18, 18)
                        .addGroup(FinancialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(FinancialAccPanelLayout.createSequentialGroup()
                                .addComponent(CheckingActiveLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CheckingStillActiveTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FinancialAccPanelLayout.createSequentialGroup()
                                .addComponent(SavingStillActiveLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SavingStillActiveTxt)))
                        .addGap(18, 18, 18)
                        .addGroup(FinancialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        FinancialAccPanelLayout.setVerticalGroup(
            FinancialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinancialAccPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FinancialAccLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FinancialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckingAccNoLabel)
                    .addComponent(CheckingAccNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckingCreaDateLabel)
                    .addComponent(CheckingCreaDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckingActiveLabel)
                    .addComponent(CheckingStillActiveTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FinancialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckingDebtLabel)
                    .addComponent(CheckingDebtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckingCreditLabel)
                    .addComponent(CheckingCreditTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FinancialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SavingAccNoLabel)
                    .addComponent(SavingAccNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SavingCreaDateLabel)
                    .addComponent(SavingCreaDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SavingStillActiveLabel)
                    .addComponent(SavingStillActiveTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FinancialAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SavingDebtLabel)
                    .addComponent(SavingDebtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SavingCreditLabel)
                    .addComponent(SavingCreditTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PersonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LicensePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CreditCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AddressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(FinancialAccPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PersonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LicensePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreditCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FinancialAccPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddStateLabel;
    private javax.swing.JTextField AddStateTxt;
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JPanel AddressPanel;
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JTextField AgeTxt;
    private javax.swing.JLabel AptNoLabel;
    private javax.swing.JTextField AptNoTxt;
    private javax.swing.JLabel BillingAddLabel;
    private javax.swing.JTextField BillingAddTxt;
    private javax.swing.JLabel CVVlabel;
    private javax.swing.JTextField CVVtxt;
    private javax.swing.JLabel CardNoLabel;
    private javax.swing.JTextField CardNoTxt;
    private javax.swing.JLabel CheckingAccNoLabel;
    private javax.swing.JTextField CheckingAccNoTxt;
    private javax.swing.JLabel CheckingActiveLabel;
    private javax.swing.JLabel CheckingCreaDateLabel;
    private javax.swing.JTextField CheckingCreaDateTxt;
    private javax.swing.JLabel CheckingCreditLabel;
    private javax.swing.JTextField CheckingCreditTxt;
    private javax.swing.JLabel CheckingDebtLabel;
    private javax.swing.JTextField CheckingDebtTxt;
    private javax.swing.JTextField CheckingStillActiveTxt;
    private javax.swing.JLabel CountryLabel;
    private javax.swing.JTextField CountryTxt;
    private javax.swing.JPanel CreditCardPanel;
    private javax.swing.JLabel DOBLabel;
    private javax.swing.JTextField DOBtxt;
    private javax.swing.JLabel ExpDateLabel;
    private javax.swing.JTextField ExpDateTxt;
    private javax.swing.JLabel ExpirationDateLabel;
    private javax.swing.JTextField ExpirationDateTxt;
    private javax.swing.JLabel FinancialAccLabel;
    private javax.swing.JPanel FinancialAccPanel;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameTxt;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JTextField GenderTxt;
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JLabel IssueDateLabel;
    private javax.swing.JTextField IssueDateTxt;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameTxt;
    private javax.swing.JLabel LicenseClassLabel;
    private javax.swing.JTextField LicenseClassTxt;
    private javax.swing.JLabel LicenseInfoLabel;
    private javax.swing.JLabel LicenseNoLabel;
    private javax.swing.JTextField LicenseNoTxt;
    private javax.swing.JPanel LicensePanel;
    private javax.swing.JPanel PersonPanel;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JTextField PhoneTxt;
    private javax.swing.JLabel ProfileLabel;
    private javax.swing.JLabel SavingAccNoLabel;
    private javax.swing.JTextField SavingAccNoTxt;
    private javax.swing.JLabel SavingCreaDateLabel;
    private javax.swing.JTextField SavingCreaDateTxt;
    private javax.swing.JLabel SavingCreditLabel;
    private javax.swing.JTextField SavingCreditTxt;
    private javax.swing.JLabel SavingDebtLabel;
    private javax.swing.JTextField SavingDebtTxt;
    private javax.swing.JLabel SavingStillActiveLabel;
    private javax.swing.JTextField SavingStillActiveTxt;
    private javax.swing.JLabel StateLabel;
    private javax.swing.JTextField StateTXT;
    private javax.swing.JLabel StreetAddLabel;
    private javax.swing.JTextField StreetAddTxt;
    private javax.swing.JLabel ZipLabel;
    private javax.swing.JTextField ZipTxt;
    private javax.swing.JLabel ccInfoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel personalInfoLabel;
    // End of variables declaration//GEN-END:variables
}
