/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.clinic;

import business.enterprise.Enterprise;
import business.organization.Organization;
import business.useraccount.UserAccount;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yizhe Liu
 */
public class ClinicWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClinicWorkAreaJPanel
     */
    private Organization organization;
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    public ClinicWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount,Enterprise enterprise, Organization organization) {
        initComponents();
        this.organization = organization;
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        
        txtV1.setText(String.valueOf(enterprise.getEnterpriseV1Quantity()));
        txtV2.setText(String.valueOf(enterprise.getEnterpriseV2Quantity()));
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblProvidors.getModel();
//        model.setRowCount(0);
        model.setValueAt("Vaccine 1", 0, 0);
        model.setValueAt("Vaccine 2", 1, 0);
        model.setValueAt(organization.getOrganizationV1Quantity(), 0, 1);
        model.setValueAt(organization.getOrganizationV2Quantity(), 1, 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        cbVaccine = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProvidors = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnUseVaccine = new javax.swing.JButton();
        lblAmount = new javax.swing.JLabel();
        lblAmount1 = new javax.swing.JLabel();
        txtV1 = new javax.swing.JTextField();
        txtV2 = new javax.swing.JTextField();
        spinnerQ = new javax.swing.JSpinner();

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("Vaccine:");

        cbVaccine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HEPATITIS", "H1N1" }));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Quantity:");

        tblProvidors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Vaccine", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProvidors);

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vaccine management - Clinic");

        btnSubmit.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnSubmit.setText("REQUEST VACCINE");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnUseVaccine.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnUseVaccine.setText("Use Vaccine");
        btnUseVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUseVaccineActionPerformed(evt);
            }
        });

        lblAmount.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblAmount.setText("H1N1:");

        lblAmount1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblAmount1.setText("HEPATITIS:");

        txtV1.setEditable(false);
        txtV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtV1ActionPerformed(evt);
            }
        });

        txtV2.setEditable(false);
        txtV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtV2ActionPerformed(evt);
            }
        });

        spinnerQ.setModel(new javax.swing.SpinnerNumberModel(20, 1, 50, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spinnerQ, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAmount1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAmount, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtV1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtV2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1)
                            .addComponent(btnUseVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(spinnerQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSubmit)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnUseVaccine)
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtV1ActionPerformed

    private void txtV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtV2ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        String v = String.valueOf(cbVaccine.getSelectedItem());
        int v1 = organization.getOrganizationV1Quantity();
        int v2 = organization.getOrganizationV2Quantity();
        int ev1 = enterprise.getEnterpriseV1Quantity();
        int ev2 = enterprise.getEnterpriseV2Quantity();
        int quantity = (int) spinnerQ.getValue();
        
        if(v.equals("HEPATITIS")){
            if (quantity > ev1) {
                JOptionPane.showMessageDialog(null, "provider don't have vaccine that much");
                return;
            }
            organization.setOrganizationV1Quantity(v1 + quantity);
            enterprise.setEnterpriseV1Quantity(ev1 - quantity);
            txtV1.setText(String.valueOf(enterprise.getEnterpriseV1Quantity()));
        }
        else if(v.equals("H1N1")){
            if (quantity > ev2) {
                JOptionPane.showMessageDialog(null, "provider don't have vaccine that much");
                return;
            }
            organization.setOrganizationV2Quantity(v2 + quantity);
            enterprise.setEnterpriseV2Quantity(ev2 - quantity);
            txtV2.setText(String.valueOf(enterprise.getEnterpriseV2Quantity()));
        }
        
        populateTable();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnUseVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUseVaccineActionPerformed
        // TODO add your handling code here:
      
        String v = String.valueOf(cbVaccine.getSelectedItem());
        int v1 = organization.getOrganizationV1Quantity();
        int v2 = organization.getOrganizationV2Quantity();
         int quantity = (int) spinnerQ.getValue();
         
         if(v.equals("V1")){
             if (quantity > v1) {
                JOptionPane.showMessageDialog(null, "our clinic don't have vaccine that much");
                return;
            }
            organization.setOrganizationV1Quantity(v1 - quantity);
        }
        else if(v.equals("V2")){
            if (quantity > v2) {
                JOptionPane.showMessageDialog(null, "our clinic don't have vaccine that much");
                return;
            }
            organization.setOrganizationV2Quantity(v2 - quantity);
        }
         populateTable();
    }//GEN-LAST:event_btnUseVaccineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUseVaccine;
    private javax.swing.JComboBox<String> cbVaccine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblAmount1;
    private javax.swing.JSpinner spinnerQ;
    private javax.swing.JTable tblProvidors;
    private javax.swing.JTextField txtV1;
    private javax.swing.JTextField txtV2;
    // End of variables declaration//GEN-END:variables
}
