/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Employee;

import Business.*;
import java.awt.CardLayout;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wenqing
 */
public class SalesPerformancePanel extends javax.swing.JPanel {
    private SupplierDirectory sd;
    private MarketOfferCatalogue moc;
    private MarketList ml;
    private PersonDirectory pd;
    private UserAccountDirectory uad;    
    private JPanel card;
    
    private DefaultTableModel dtm;

    public SalesPerformancePanel(JPanel cardPanel, SupplierDirectory sd, MarketOfferCatalogue moc, MarketList ml, UserAccountDirectory uad, PersonDirectory pd) {
        initComponents();
        this.card = cardPanel;
        this.sd = sd;
        this.moc =moc;
        this.ml = ml;
        this.uad = uad;
        this.pd =pd;
        populateCombo();
        populateTable();
        populateTxt();
    }
    
    private void populateTxt(){
        HashMap<Product, Double> map = ml.getMap();   
        if(map.size()<3){
            JOptionPane.showMessageDialog(null,"Please place more orders before comparing sales performance");
            return;
        }
        List<Double> values = new ArrayList<Double>(map.values());
        Collections.sort(values, Collections.reverseOrder());
        Product display1 = null;
        Double gap1 = 0.0;
        Product display2 = null;
        Double gap2 = 0.0;
        Product display3 = null;
        Double gap3 = 0.0;
        for(Product p: map.keySet()){
            if(map.get(p)==values.get(0)){
                display1 = p;
                gap1 = values.get(0);
            }
            if(map.get(p)==values.get(1)){
                display2 = p;
                gap2 = values.get(1);
            }
            if(map.get(p)==values.get(2)){
                display3 = p;
                gap3 = values.get(2);
            }
        }    
        P1Txt.setText(display1.getName());
        P2Txt.setText(display2.getName());
        P3Txt.setText(display3.getName());
        P1GapTxt.setText(Double.toString(gap1));
        P2GapTxt.setText(Double.toString(gap2));
        P3GapTxt.setText(Double.toString(gap3));
    }
    
    private void populateCombo(){
        for (Supplier s: sd.getList()){
            SupplierCombo.addItem(s);
        }
        for (Market m: ml.getList()){
            MarketCombo.addItem(m);
        }        
    }
    
    private void populateTable(){
        //DefaultTableModel dtm = (DefaultTableModel)PerformanceTable.getModel();
        dtm = (DefaultTableModel)PerformanceTable.getModel();
        dtm.setRowCount(0);
        
        Object row[] = new Object[7];
        for(Person p: pd.getList()){
            if(p.getUa().getRole().equals("sales person")){
                row[0] = p;
                double FinRev = 0;
                double FinGap = 0;
                for(Order ord: p.getOrderList()){
                    if(ord.getCustomer().getM().getMarketName().equals("Finance")){
                        double rev = ord.getRevenue();
                        double gap = ord.getGap();
                        FinRev += rev;
                        FinGap += gap;
                    }        
                }
                row[1] = FinRev;
                row[2] = FinGap;
                
                double EduRev = 0;
                double EduGap = 0;
                for(Order ord: p.getOrderList()){
                    if(ord.getCustomer().getM().getMarketName().equals("Education")){
                        double rev = ord.getRevenue();
                        double gap = ord.getGap();
                        EduRev += rev;
                        EduGap += gap;
                    }        
                }
                row[3] = FinRev;
                row[4] = FinGap;
                
                row[5] = p.getTotalRevenue();
                row[6] = p.getTotalGap();    
                dtm.addRow(row);
            }            
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SupplierCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        MarketCombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        TotalRevTxt = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        MktRevTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TotalGapTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        MktGapTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        PerformanceTable = new javax.swing.JTable();
        AboveBut = new javax.swing.JButton();
        BelowBut = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        P2Txt = new javax.swing.JTextField();
        P2GapTxt = new javax.swing.JTextField();
        P3Txt = new javax.swing.JTextField();
        P3GapTxt = new javax.swing.JTextField();
        P1Txt = new javax.swing.JTextField();
        P1GapTxt = new javax.swing.JTextField();
        SupGoBut = new javax.swing.JButton();
        MktGoBut = new javax.swing.JButton();
        ClearBut = new javax.swing.JButton();
        BackBut = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Supplier:");

        SupplierCombo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Market:");

        MarketCombo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Total Revenue:");

        TotalRevTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label.setText("Market Revenue:");

        MktRevTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Gap:");

        TotalGapTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Gap:");

        MktGapTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        PerformanceTable.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PerformanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sales Person", "Fin. Rev.", "Fin. Gap", "Educ. Rev.", "Fin. Gap", "Total Rev.", "Total. Gap"
            }
        ));
        jScrollPane1.setViewportView(PerformanceTable);

        AboveBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AboveBut.setText("Above Target");
        AboveBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboveButActionPerformed(evt);
            }
        });

        BelowBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BelowBut.setText("Below Target");
        BelowBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BelowButActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Top 3 Products above Target:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Gap:");

        P2Txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        P2GapTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        P3Txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        P3GapTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        P1Txt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        P1GapTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        SupGoBut.setText("Go");
        SupGoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupGoButActionPerformed(evt);
            }
        });

        MktGoBut.setText("Go");
        MktGoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MktGoButActionPerformed(evt);
            }
        });

        ClearBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ClearBut.setText("Clear");
        ClearBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButActionPerformed(evt);
            }
        });

        BackBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BackBut.setText("Back<<");
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(SupplierCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(TotalRevTxt)
                                            .addComponent(TotalGapTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(label)
                                                    .addComponent(jLabel6)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SupGoBut)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(MktRevTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MarketCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(MktGapTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MktGoBut))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel7)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(BackBut)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(P1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(P1GapTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(P2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(P2GapTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(P3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(P3GapTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 12, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(AboveBut, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(ClearBut, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(BelowBut, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(SupplierCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MarketCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(SupGoBut)
                    .addComponent(MktGoBut))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TotalRevTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MktRevTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TotalGapTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MktGapTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AboveBut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BelowBut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearBut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(P2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(P2GapTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(P3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(P3GapTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(P1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(P1GapTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(BackBut))))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BelowButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BelowButActionPerformed
        dtm.setRowCount(0);
        Object row[] = new Object[7];
        for(Person p: pd.getList()){
            if(p.getUa().getRole().equals("sales person") && p.getTotalGap()<0){
                row[0] = p;
                double FinRev = 0;
                double FinGap = 0;
                for(Order ord: p.getOrderList()){
                    if(ord.getCustomer().getM().getMarketName().equals("Finance")){
                        double rev = ord.getRevenue();
                        double gap = ord.getGap();
                        FinRev += rev;
                        FinGap += gap;
                    }        
                }
                row[1] = FinRev;
                row[2] = FinGap;
                
                double EduRev = 0;
                double EduGap = 0;
                for(Order ord: p.getOrderList()){
                    if(ord.getCustomer().getM().getMarketName().equals("Education")){
                        double rev = ord.getRevenue();
                        double gap = ord.getGap();
                        EduRev += rev;
                        EduGap += gap;
                    }        
                }
                row[3] = FinRev;
                row[4] = FinGap;
                
                row[5] = p.getTotalRevenue();
                row[6] = p.getTotalGap();    
                dtm.addRow(row);
            }        
        }
    }//GEN-LAST:event_BelowButActionPerformed

    private void SupGoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupGoButActionPerformed
        Supplier s = (Supplier)SupplierCombo.getSelectedItem();
        double totalRev = 0;
        double totalGap = 0;
        for(Market mkt: ml.getList()){
            double rev = mkt.calculateRev();
            double gap = mkt.calculateGap(); 
            totalRev += rev;
            totalGap += gap;
        }
        TotalRevTxt.setText(Double.toString(totalRev));
        TotalGapTxt.setText(Double.toString(totalGap));
    }//GEN-LAST:event_SupGoButActionPerformed

    private void MktGoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MktGoButActionPerformed
        Market m = (Market)MarketCombo.getSelectedItem();
        double mktRev = m.calculateRev();
        double mktGap = m.calculateGap();
        MktRevTxt.setText(Double.toString(mktRev));
        MktGapTxt.setText(Double.toString(mktGap));
    }//GEN-LAST:event_MktGoButActionPerformed

    private void ClearButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButActionPerformed
        populateTable();
    }//GEN-LAST:event_ClearButActionPerformed

    private void AboveButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboveButActionPerformed
        dtm.setRowCount(0);
        Object row[] = new Object[7];
        for(Person p: pd.getList()){
            if(p.getUa().getRole().equals("sales person") && p.getTotalGap()>0){
                row[0] = p;
                double FinRev = 0;
                double FinGap = 0;
                for(Order ord: p.getOrderList()){
                    if(ord.getCustomer().getM().getMarketName().equals("Finance")){
                        double rev = ord.getRevenue();
                        double gap = ord.getGap();
                        FinRev += rev;
                        FinGap += gap;
                    }        
                }
                row[1] = FinRev;
                row[2] = FinGap;
                
                double EduRev = 0;
                double EduGap = 0;
                for(Order ord: p.getOrderList()){
                    if(ord.getCustomer().getM().getMarketName().equals("Education")){
                        double rev = ord.getRevenue();
                        double gap = ord.getGap();
                        EduRev += rev;
                        EduGap += gap;
                    }        
                }
                row[3] = FinRev;
                row[4] = FinGap;
                
                row[5] = p.getTotalRevenue();
                row[6] = p.getTotalGap();    
                dtm.addRow(row);
            }
        }
    }//GEN-LAST:event_AboveButActionPerformed

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
        card.remove(this);       
        CardLayout layout = (CardLayout) card.getLayout();
        layout.previous(card);
    }//GEN-LAST:event_BackButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboveBut;
    private javax.swing.JButton BackBut;
    private javax.swing.JButton BelowBut;
    private javax.swing.JButton ClearBut;
    private javax.swing.JComboBox MarketCombo;
    private javax.swing.JTextField MktGapTxt;
    private javax.swing.JButton MktGoBut;
    private javax.swing.JTextField MktRevTxt;
    private javax.swing.JTextField P1GapTxt;
    private javax.swing.JTextField P1Txt;
    private javax.swing.JTextField P2GapTxt;
    private javax.swing.JTextField P2Txt;
    private javax.swing.JTextField P3GapTxt;
    private javax.swing.JTextField P3Txt;
    private javax.swing.JTable PerformanceTable;
    private javax.swing.JButton SupGoBut;
    private javax.swing.JComboBox SupplierCombo;
    private javax.swing.JTextField TotalGapTxt;
    private javax.swing.JTextField TotalRevTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}