/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Employee;

import Business.MarketList;
import Business.MarketOfferCatalogue;
import Business.Person;
import Business.PersonDirectory;
import Business.SupplierDirectory;
import Business.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Wenqing
 */
public class SystemAdminPanel extends javax.swing.JPanel {
    private SupplierDirectory sd;
    private MarketOfferCatalogue moc;
    private MarketList ml;
    private PersonDirectory pd;
    private UserAccountDirectory uad;    
    private JPanel card;

    public SystemAdminPanel(JPanel cardPanel, Person p, SupplierDirectory sd, MarketOfferCatalogue moc, MarketList ml, UserAccountDirectory uad, PersonDirectory pd) {
        initComponents();
        this.card = cardPanel;
        this.sd = sd;
        this.moc =moc;
        this.ml = ml;
        this.uad = uad;
        this.pd =pd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageSupplierBut = new javax.swing.JButton();
        ManageMarketOfferBut = new javax.swing.JButton();
        ViewPerformanceBut = new javax.swing.JButton();
        ManageAccountBut = new javax.swing.JButton();

        ManageSupplierBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ManageSupplierBut.setText("Manage Supplier");
        ManageSupplierBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageSupplierButActionPerformed(evt);
            }
        });

        ManageMarketOfferBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ManageMarketOfferBut.setText("Manage Market Offer");
        ManageMarketOfferBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageMarketOfferButActionPerformed(evt);
            }
        });

        ViewPerformanceBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ViewPerformanceBut.setText("View Sales Performance");
        ViewPerformanceBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPerformanceButActionPerformed(evt);
            }
        });

        ManageAccountBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ManageAccountBut.setText("Manage UserAccount");
        ManageAccountBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageAccountButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ManageSupplierBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ManageMarketOfferBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewPerformanceBut, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManageAccountBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(ManageSupplierBut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(ManageMarketOfferBut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(ManageAccountBut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ViewPerformanceBut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ManageAccountButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageAccountButActionPerformed
        ManageUserAccountPanel muap = new ManageUserAccountPanel(card,sd,moc,ml,uad,pd);
        card.add("ManageUserAccountPanel", muap);
        CardLayout lo = (CardLayout) card.getLayout();
        lo.next(card);
    }//GEN-LAST:event_ManageAccountButActionPerformed

    private void ViewPerformanceButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPerformanceButActionPerformed
        SalesPerformancePanel spp = new SalesPerformancePanel(card,sd,moc,ml,uad,pd);
        card.add("SalesPerformancePanel", spp);
        CardLayout lo = (CardLayout) card.getLayout();
        lo.next(card);
    }//GEN-LAST:event_ViewPerformanceButActionPerformed

    private void ManageMarketOfferButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageMarketOfferButActionPerformed
        ManageMarketOfferPanel mmop = new ManageMarketOfferPanel(card,sd,moc,ml,uad,pd);
        card.add("ManageMarketOfferPanel", mmop);
        CardLayout lo = (CardLayout) card.getLayout();
        lo.next(card);
    }//GEN-LAST:event_ManageMarketOfferButActionPerformed

    private void ManageSupplierButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageSupplierButActionPerformed
        ManageSupplierPanel msp = new ManageSupplierPanel(card,sd,moc,ml,uad,pd);
        card.add("ManageSupplierPanel", msp);
        CardLayout lo = (CardLayout) card.getLayout();
        lo.next(card);
    }//GEN-LAST:event_ManageSupplierButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageAccountBut;
    private javax.swing.JButton ManageMarketOfferBut;
    private javax.swing.JButton ManageSupplierBut;
    private javax.swing.JButton ViewPerformanceBut;
    // End of variables declaration//GEN-END:variables
}
