/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;
import Business.*;
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author Wenqing
 */
public class MainFrame extends javax.swing.JFrame {
    private MasterFlightSchedule ms;
    private AirlinerDirectory ad;
    private CustomerDirectory cd;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        ms = new MasterFlightSchedule();
        ad = new AirlinerDirectory();
        cd = new CustomerDirectory();
        initComponents();        
    }
    
    private void loadFlights(){
        String csv = "C:\\Users\\Wenqing\\Desktop\\AAFlight.csv";
        BufferedReader br =  null;        
        FlightSchedule AASchedule = ms.addSchedule();
        AASchedule.setAirlinername("AmericaAirline");
        try{
            br = new BufferedReader(new FileReader(csv));
            String row = "";              
            while((row = br.readLine())!=null){                
                String item[] = row.split(",");
                Flight f = AASchedule.addFlight();              
                f.setFlightNo(item[0]);
                f.setFrom(item[1]);
                f.setTo(item[2]);
                f.setDepartureTime(item[3]);
                f.setArrivalTime(item[4]);
                f.setDate(item[5]);
                f.setTimeOfDay(item[6]);                      
            }       
        }
        catch (Exception e){
            e.printStackTrace();
        }
        
        String csv2 = "C:\\Users\\Wenqing\\Desktop\\UAFlight.csv";              
        FlightSchedule UASchedule = ms.addSchedule();
        UASchedule.setAirlinername("UnitedAirline");
        try{
            br = new BufferedReader(new FileReader(csv2));
            String row = "";              
            while((row = br.readLine())!=null){                
                String item[] = row.split(",");
                Flight f = UASchedule.addFlight();              
                f.setFlightNo(item[0]);
                f.setFrom(item[1]);
                f.setTo(item[2]);
                f.setDepartureTime(item[3]);
                f.setArrivalTime(item[4]);
                f.setDate(item[5]);
                f.setTimeOfDay(item[6]);                      
            }       
        }
        catch (Exception e){
            e.printStackTrace();
        }
        
        
        JOptionPane.showMessageDialog(null, "Flights Uploaded");
    }
    
    private void loadAirliners(){
        String csv = "C:\\Users\\Wenqing\\Desktop\\Airliner.csv";
        BufferedReader br =  null;
        try{
            br = new BufferedReader(new FileReader(csv));
            String row = "";              
            while((row = br.readLine())!=null){                
                String item[] = row.split(",");
                
                Airliner air = ad.addAirliner();                
                air.setName(item[0]);
            }       
        }
        catch (Exception e){
            e.printStackTrace();
        }
         JOptionPane.showMessageDialog(null, "Airliners Uploaded");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        CardPanel = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        AgencyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        CardPanel.setLayout(new java.awt.CardLayout());
        SplitPane.setRightComponent(CardPanel);

        TopPanel.setPreferredSize(new java.awt.Dimension(400, 100));
        TopPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgencyButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AgencyButton.setText("Travel Agency");
        AgencyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgencyButtonActionPerformed(evt);
            }
        });
        TopPanel.add(AgencyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 180, 60));

        SplitPane.setTopComponent(TopPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgencyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgencyButtonActionPerformed
        loadAirliners();
        loadFlights();
        
        StartingPanel sp = new StartingPanel(ms,ad,cd, CardPanel);
        CardPanel.add("Starting Panel", sp);
        CardLayout lo = (CardLayout) CardPanel.getLayout();
        lo.next(CardPanel); 
        
        for(Airliner air: ad.getAirliner()){
            String name = air.getName();
            for(FlightSchedule fs: ms.getMfs()){
                if(fs.getAirlinername().equals(name)){
                    air.setFs(fs);
                    System.out.println(fs);
                }
            }            
        }
    }//GEN-LAST:event_AgencyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgencyButton;
    private javax.swing.JPanel CardPanel;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JPanel TopPanel;
    // End of variables declaration//GEN-END:variables
}