/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.*;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.util.*;

/**
 *
 * @author Wenqing
 */
public class RegisterAirlinePanel extends javax.swing.JPanel {
    private MasterFlightSchedule ms;
    private AirlinerDirectory ad;
    private CustomerDirectory cd;
    private JPanel CardPanel;
    private DefaultTableModel dtm;
    

    /**
     * Creates new form RegisterAirlinePanel
     */

    public RegisterAirlinePanel(MasterFlightSchedule ms, AirlinerDirectory ad, CustomerDirectory cd, JPanel CardPanel) {
        this.ms = ms;
        this.ad = ad;
        this.cd = cd;
        this.CardPanel = CardPanel;
        initComponents();
        populateTable();
    }
    private void populateTable(){
        dtm = (DefaultTableModel)AirlinerTable.getModel();
        dtm.setRowCount(0);
        
        for(Airliner air: ad.getAirliner()){
            Object row[] = new Object[2];
                          
            row[0] = air;
            row[1] = air.getDateCreated();
           
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AirlinerTable = new javax.swing.JTable();
        NewBut = new javax.swing.JButton();
        ViewBut = new javax.swing.JButton();
        ManageFlightBut = new javax.swing.JButton();
        BackBut = new javax.swing.JButton();
        RefreshBut = new javax.swing.JButton();

        AirlinerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name of Airliner", "Date Created"
            }
        ));
        jScrollPane1.setViewportView(AirlinerTable);

        NewBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NewBut.setText("New");
        NewBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewButActionPerformed(evt);
            }
        });

        ViewBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ViewBut.setText("View");
        ViewBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButActionPerformed(evt);
            }
        });

        ManageFlightBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ManageFlightBut.setText("Manage Flight Schedule");
        ManageFlightBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageFlightButActionPerformed(evt);
            }
        });

        BackBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BackBut.setText("<< Back");
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });

        RefreshBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RefreshBut.setText("Refresh");
        RefreshBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(NewBut, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(RefreshBut)
                        .addGap(53, 53, 53)
                        .addComponent(ViewBut, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(BackBut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ManageFlightBut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(ManageFlightBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackBut)
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewBut)
                    .addComponent(ViewBut)
                    .addComponent(RefreshBut))
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
        CardPanel.remove(this);
        CardLayout layout = (CardLayout) CardPanel.getLayout();
        layout.previous(CardPanel);
    }//GEN-LAST:event_BackButActionPerformed

    private void NewButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewButActionPerformed
        Airliner air = ad.addAirliner();
        CreateAirlinerPanel cap = new CreateAirlinerPanel(ms,ad,cd, CardPanel,air);
        CardPanel.add("CreateAirlinerPanel", cap);
        CardLayout lo = (CardLayout) CardPanel.getLayout();
        lo.next(CardPanel);
    }//GEN-LAST:event_NewButActionPerformed

    private void ViewButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButActionPerformed
        int selectedRow = AirlinerTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"please select a row");
        }
        else{
            Airliner air = (Airliner) AirlinerTable.getValueAt(selectedRow, 0);
            ViewAirlinerPanel vap = new ViewAirlinerPanel(ms,ad,cd, CardPanel, air);
            
            CardPanel.add("ViewAirlinerPanel", vap);
            CardLayout lo = (CardLayout) CardPanel.getLayout();
            lo.next(CardPanel);           
            
            vap.setNameTxt(air.getName());            
            vap.setDateTxt(air.getDateCreated());
        }        
    }//GEN-LAST:event_ViewButActionPerformed
   
    private void ManageFlightButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageFlightButActionPerformed
        int selectedRow = AirlinerTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"please select a row");
        }
        else{
            Airliner air = (Airliner) AirlinerTable.getValueAt(selectedRow, 0);            
            
            ManageFlightPanel mfp = new ManageFlightPanel(ms,ad,cd, CardPanel, air);            
            CardPanel.add("UpdateFlightPanel", mfp);
            CardLayout lo = (CardLayout) CardPanel.getLayout();
            lo.next(CardPanel);             
        }       
    }//GEN-LAST:event_ManageFlightButActionPerformed

    private void RefreshButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButActionPerformed
        populateTable();
    }//GEN-LAST:event_RefreshButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AirlinerTable;
    private javax.swing.JButton BackBut;
    private javax.swing.JButton ManageFlightBut;
    private javax.swing.JButton NewBut;
    private javax.swing.JButton RefreshBut;
    private javax.swing.JButton ViewBut;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}