/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Business;
import Business.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wenqing
 */
public class ManageUserPanel extends javax.swing.JPanel {
    private Business b;
    private JPanel panel;
    
    private DefaultTableModel dtm; 

    /**
     * Creates new form ManageUserAccount
     */
    public ManageUserPanel(Business b, JPanel panel) {            
        initComponents();
        this.b=b;
        this.panel=panel;
        populateTable();        
    }
        
    public void populateTable(){
        dtm = (DefaultTableModel)DisplayTable.getModel();        
        dtm.setRowCount(0);  
        
        for(UserAccount ua: b.getUad().getList()){
            Object[] row = new Object[3];
            row[0] = ua;
            row[1] = ua.getPassword();
            row[2] = ua.getRole();
            
            dtm.addRow(row);
        }            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayTable = new javax.swing.JTable();
        FindBut = new javax.swing.JButton();
        AddBut = new javax.swing.JButton();
        UpdateBut = new javax.swing.JButton();
        RemoveBut = new javax.swing.JButton();

        DisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserName", "Password", "Role"
            }
        ));
        jScrollPane1.setViewportView(DisplayTable);

        FindBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        FindBut.setText("Find User ");
        FindBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindButActionPerformed(evt);
            }
        });

        AddBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AddBut.setText("Add User");
        AddBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButActionPerformed(evt);
            }
        });

        UpdateBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UpdateBut.setText("Update User");
        UpdateBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButActionPerformed(evt);
            }
        });

        RemoveBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RemoveBut.setText("Remove User");
        RemoveBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddBut, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(FindBut, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UpdateBut, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RemoveBut, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FindBut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AddBut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UpdateBut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RemoveBut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButActionPerformed
        int row = DisplayTable.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null,"Please select a row");
            return;
        }
        UserAccount ua = (UserAccount)DisplayTable.getValueAt(row, 0);
        
        UpdateUserPanel uup = new UpdateUserPanel(b, panel, ua);
        panel.add("UpdateUserPanel", uup);
        CardLayout lo = (CardLayout) panel.getLayout();
        lo.next(panel);
    }//GEN-LAST:event_UpdateButActionPerformed

    private void AddButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButActionPerformed
        
        NewUserPanel nup = new NewUserPanel(b, panel);
        panel.add("NewUserPanel", nup);
        CardLayout lo = (CardLayout) panel.getLayout();
        lo.next(panel);
        populateTable();
    }//GEN-LAST:event_AddButActionPerformed

    private void FindButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindButActionPerformed
        FindUserPanel fup = new FindUserPanel(b, panel);
        panel.add("FindUserPanel", fup);
        CardLayout lo = (CardLayout) panel.getLayout();
        lo.next(panel);
        populateTable();
    }//GEN-LAST:event_FindButActionPerformed

    private void RemoveButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButActionPerformed
        int row = DisplayTable.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null,"Please select a row");
            return;
        }
        
        UserAccount ua = (UserAccount)DisplayTable.getValueAt(row, 0);
        b.getUad().removeAccount(ua);
        populateTable();
    }//GEN-LAST:event_RemoveButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBut;
    private javax.swing.JTable DisplayTable;
    private javax.swing.JButton FindBut;
    private javax.swing.JButton RemoveBut;
    private javax.swing.JButton UpdateBut;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
