/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Supplier;

import Business.*;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Wenqing
 */
public class ChooseSupplierPanel extends javax.swing.JPanel {
    JPanel card;
    SupplierDirectory sd;


    public ChooseSupplierPanel(JPanel CardPanel, SupplierDirectory dir) {
        initComponents();
        this.card = CardPanel;
        this.sd = dir;
        loadCombo();
    }
    
    private void loadCombo(){
        for (Supplier s: sd.getList()){
            SupplierCombo.addItem(s); 
            System.out.println("name is: " + s.getSupplierName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SupplierCombo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        SupplierBut = new javax.swing.JButton();

        SupplierCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierComboActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Choose Supplier:");
        jLabel1.setToolTipText("");

        SupplierBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SupplierBut.setText("Go to Supplier");
        SupplierBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addGap(91, 91, 91)
                .addComponent(SupplierCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SupplierBut, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupplierCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(98, 98, 98)
                .addComponent(SupplierBut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SupplierButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierButActionPerformed
    Supplier s = (Supplier) SupplierCombo.getSelectedItem();
    SupplierDetailPanel sdp = new SupplierDetailPanel(card,s);
    card.add("SupplierDetailPanel", sdp);
    CardLayout lo = (CardLayout) card.getLayout();
    lo.next(card);   
    }//GEN-LAST:event_SupplierButActionPerformed

    private void SupplierComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SupplierComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SupplierBut;
    private javax.swing.JComboBox SupplierCombo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
