/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.*;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Wenqing
 */
public class ManageCustomerPanel extends javax.swing.JPanel {
    private MasterFlightSchedule ms;
    private AirlinerDirectory ad;
    private CustomerDirectory cd;
    private JPanel CardPanel;
    private DefaultTableModel dtm;
    
    

    /**
     * Creates new form ManageCustomerPanel
     */
    public ManageCustomerPanel(MasterFlightSchedule ms, AirlinerDirectory ad, CustomerDirectory cd, JPanel CardPanel) {
        this.ms = ms;
        this.ad = ad;
        this.cd = cd;
        this.CardPanel = CardPanel;        
        initComponents();
        populateTable();
    }
    
    private void populateTable(){
        dtm = (DefaultTableModel)FlightTable.getModel();
        dtm.setRowCount(0);
        
        for(Airliner air: ad.getAirliner()){
            FlightSchedule fs = air.getFs();
            if(fs!=null){
                for(Flight f: fs.getSchedule()){                
                    Object row[] = new Object[8];                          
                    row[0] = air.getName();
                    row[1] = f;
                    row[2] = f.getFrom();
                    row[3] = f.getTo();
                    row[4] = f.getDepartureTime();
                    row[5] = f.getArrivalTime();
                    row[6] = f.getDate();
                    row[7] = f.getTimeOfDay();
                    dtm.addRow(row);
                 }                   
            }                    
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BookBut = new javax.swing.JButton();
        SearchBut = new javax.swing.JButton();
        BackBut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        FlightTable = new javax.swing.JTable();
        FromTxt = new javax.swing.JTextField();
        ToTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ToDTxt = new javax.swing.JTextField();
        ClearBut = new javax.swing.JButton();

        BookBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BookBut.setText("Book Reservation");
        BookBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookButActionPerformed(evt);
            }
        });

        SearchBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SearchBut.setText("Search Flight");
        SearchBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButActionPerformed(evt);
            }
        });

        BackBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BackBut.setText("<< Back");
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });

        FlightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner", "Flight No", "From", "To", "Dep Time", "Arr Time", "Date", "Time Of Day"
            }
        ));
        jScrollPane1.setViewportView(FlightTable);

        jLabel1.setText("from:");

        jLabel2.setText("to:");

        jLabel3.setText("time of day:");
        jLabel3.setToolTipText("");

        ClearBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ClearBut.setText("Clear");
        ClearBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackBut)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(FromTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ToDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ToTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BookBut, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(SearchBut, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(ClearBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackBut)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FromTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ToTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(ClearBut)))
                    .addComponent(SearchBut))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(BookBut))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
        CardPanel.remove(this);
        CardLayout layout = (CardLayout) CardPanel.getLayout();
        layout.previous(CardPanel);
    }//GEN-LAST:event_BackButActionPerformed

    private void SearchButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButActionPerformed
        String from = FromTxt.getText();
        String to = ToTxt.getText();
        String TimeOfDay = ToDTxt.getText();
        
        dtm.setRowCount(0);   
        Object row[] = new Object[8];  
        
        HashMap <String, ArrayList<Flight>> map = ms.searchMasterSchedule(from, to, TimeOfDay);
        if(map.isEmpty()){
            JOptionPane.showMessageDialog(null, "No flights found under such criteria");
        }
         
        for(String s:map.keySet()){
            ArrayList<Flight> flist = map.get(s);
             for(Flight f: flist){                                        
                row[0] = s;
                row[1] = f;
                row[2] = f.getFrom();
                row[3] = f.getTo();
                row[4] = f.getDepartureTime();
                row[5] = f.getArrivalTime();
                row[6] = f.getDate();
                row[7] = f.getTimeOfDay();
                dtm.addRow(row);                
            }                         
        }
    }//GEN-LAST:event_SearchButActionPerformed

    private void BookButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookButActionPerformed
        int selectedRow = FlightTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"please select a row");
        }
        else{                
            Flight f = (Flight)FlightTable.getValueAt(selectedRow, 1);
            BookFlightPanel bfp = new BookFlightPanel(ms,ad,cd, CardPanel,f);
            CardPanel.add("BookFlightPanel", bfp);
            CardLayout lo = (CardLayout) CardPanel.getLayout();
            lo.next(CardPanel);            
        }        
    }//GEN-LAST:event_BookButActionPerformed

    private void ClearButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButActionPerformed
        populateTable();
        FromTxt.setText("");
        ToTxt.setText("");
        ToDTxt.setText("");
    }//GEN-LAST:event_ClearButActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBut;
    private javax.swing.JButton BookBut;
    private javax.swing.JButton ClearBut;
    private javax.swing.JTable FlightTable;
    private javax.swing.JTextField FromTxt;
    private javax.swing.JButton SearchBut;
    private javax.swing.JTextField ToDTxt;
    private javax.swing.JTextField ToTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
